# - hosts: localhost
#   vars:
#     ansible_python_interpreter: /usr/bin/python3

#   vars_files:
#   - host_vars/backend_vars.yaml
#   gather_facts: true

#   roles:
#     - common
#     - open-port

- hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_user: ubuntu
    ansible_ssh_private_key_file: ../../empty.pem
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no' # make sure ssh will not fail

  vars_files:
  - host_vars/backend_vars.yaml
  gather_facts: true

  roles:
    - backend-files