---

- name: curl docker install shell
  become: yes
  shell: curl -fsSL https://get.docker.com -o /home/ubuntu/data/get-docker.sh

- name: sh install docker
  become: yes
  shell: sh /home/ubuntu/data/get-docker.sh

- name: append user ubuntu to docker
  become: yes
  shell: usermod -aG docker ubuntu

- name: install docker-compose
  become: yes
  apt:
    name: ['docker-compose']
    state: latest

- name: add docker draemon proxy directory
  become: yes
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory

- name: copy proxy file to instance
  become: yes
  copy:
    src: '{{docker-proxy-file}}'
    dest: "/etc/systemd/system/docker.service.d/"

- name: flush draemon
  become: yes
  shell: systemctl daemon-reload

- name: restar docker
  become: yes
  shell: systemctl restart docker

# - name: touch_text
#   become: yes
#   file:
#     path: /home/ubuntu/test
#     state: touch
#     mode: u+rwx
#     owner: ubuntu