# ! instance preference
availability_zone: melbourne-qh2-uom
# instance_network: qh2-uom-internal
instance_flavor: uom.mse.2c9g
instance_image: f8b79936-6616-4a22-b55d-0d0a1d27bceb # NeCTAR Ubuntu 18.04 LTS (Bionic) amd64 (with Docker)

# ! volume
volumes:
  - vol_name: instance1-vol
    vol_size: 64
    device: /dev/vdb
    mountpoint: /home/ubuntu/data/

# ! security group
security-groups:
  - name: shi_hu_hu
    description: "dei ci ci, e xin xin"
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0
  - name: he_tui_tui_pei
    description: "rang wo fang wen!"
    protocol: tcp
    port_range_min: 80
    port_range_max: 80
    remote_ip_prefix: 0.0.0.0/0

# ! instance
instances:
  - name: instance1
    security-groups: ['shi_hu_hu', 'he_tui_tui_pei']
    volume_ids: '{ instance1_volumes|default([]) }'
    volumes: [instance1-vol]