couchdb:
 - name: couchdb
   user: admin
   pass: admin
   version: 3.0.0
   cookie: a192aeb9904e6590849337933b000c99

security_groups:
  - name: kou_chi_db1
    description: "wo wo wo, shua la la, hong long long"
    protocol: tcp
    port_range_min: 5984
    port_range_max: 5984
    remote_ip_prefix: 0.0.0.0/0

  - name: kou_chi_db2
    description: "wo wo wo, shua la la, hong long long"
    protocol: tcp
    port_range_min: 4369
    port_range_max: 4369
    remote_ip_prefix: 0.0.0.0/0

  - name: kou_chi_db3
    description: "wo wo wo, shua la la, hong long long"
    protocol: tcp
    port_range_min: 9099
    port_range_max: 9201
    remote_ip_prefix: 0.0.0.0/0