- hosts: localhost
  vars:
    ansible_python_interpreter: /usr/bin/python3
  vars_files:
  - host_vars/create_instance_multi.yaml
  gather_facts: true

  roles:
    - role: common
    - role: image
    - role: volume
    - role: security-group
    - role: instance



